### ISSUE TITLE
Navržení a tisknutí dokladů

### ISSUE THREAD

**Issue by Salic99** [Salic99/Renato.cz#5]

**Comment by Morffeus** [comment]
Formulář je přychystán na tisknutí, je třeba domyslet znacku pro zlato (585/1000)

**Comment by Morffeus** [comment]
Shopify orderPrint buguje neotevře se tisk

**Comment by Salic99** [comment]
@Morffeus u tisknuti zálohového dokladu nefunguje Customer položka
